/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;

/**
 *
 * @author pared
 */
public class AlquilerAutos extends javax.swing.JDialog {

    /**
     * Creates new form AlquilerAutos
     * @param parent
     * @param modal
     */
    String ruta;
    public AlquilerAutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ruta = "src/datos/autosAlquilados.txt";
        Helper.llenarTabla4(tblTablaAlquilar, ruta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbAlquilar1 = new javax.swing.JButton();
        cmbAlquilar2 = new javax.swing.JButton();
        cmbAlquilar3 = new javax.swing.JButton();
        cmbAlquilar4 = new javax.swing.JButton();
        cmbAlquilar5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaAlquilar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/renault-logan-2008-03.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 100));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 100, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 150, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Volkswagen-Gol-power-1.4.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 140, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siena-frente-md.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/livina_1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 150, 110));

        cmbAlquilar1.setText("Alquilar");
        cmbAlquilar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        cmbAlquilar2.setText("Alquilar");
        cmbAlquilar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        cmbAlquilar3.setText("Alquilar");
        cmbAlquilar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar3ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        cmbAlquilar4.setText("Alquilar");
        cmbAlquilar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar4ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        cmbAlquilar5.setText("Alquilar");
        cmbAlquilar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar5ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        tblTablaAlquilar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Automovil", "Fecha", "Horas Alquiladas", "Dinero a Pagar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTablaAlquilar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 710, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlquilar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar1ActionPerformed
         DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
            a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar1ActionPerformed

    private void cmbAlquilar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar2ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
            a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar2ActionPerformed

    private void cmbAlquilar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar3ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
            a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar3ActionPerformed

    private void cmbAlquilar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar4ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
            a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar4ActionPerformed

    private void cmbAlquilar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar5ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
        a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlquilerAutos dialog = new AlquilerAutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbAlquilar1;
    private javax.swing.JButton cmbAlquilar2;
    private javax.swing.JButton cmbAlquilar3;
    private javax.swing.JButton cmbAlquilar4;
    private javax.swing.JButton cmbAlquilar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTablaAlquilar;
    // End of variables declaration//GEN-END:variables
}
