/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import clases.Autos;
import clases.Helper;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jparedes2
 */
public class AutosNuevos extends javax.swing.JDialog {
    /**
     * Creates new form AutosNuevos
     */
         String ruta;
        ObjectOutputStream salida;
        ArrayList<Autos> auto;
    public AutosNuevos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       ruta = "src/datos/autos.txt";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutosNuevos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbMarca = new javax.swing.JComboBox();
        cmbComprar = new javax.swing.JButton();
        cmbListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAutosNuevos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Tipo Marca", "Modelo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAutosNuevos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAutosNuevosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAutosNuevos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 384, 259));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Automoviles Nuevos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chevrolet", "Ford", "Renault", "Nissan", "Mazda", "Audi", "Ferrari", "Lamborghini", " " }));
        cmbMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMarcaItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmbComprar.setText("Comprar");
        cmbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbComprarActionPerformed(evt);
            }
        });
        jPanel2.add(cmbComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cmbListar.setText("Listar");
        cmbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListarActionPerformed(evt);
            }
        });
        jPanel2.add(cmbListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 110, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 600, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListarActionPerformed
        String marca =cmbMarca.getSelectedItem().toString();
        Helper.listadoPorMarca(tblAutosNuevos, ruta, marca);
    }//GEN-LAST:event_cmbListarActionPerformed

    private void cmbMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMarcaItemStateChanged
        String marca =cmbMarca.getSelectedItem().toString();
        Helper.listadoPorMarca(tblAutosNuevos, ruta, marca);
    }//GEN-LAST:event_cmbMarcaItemStateChanged

    private void cmbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbComprarActionPerformed
          int op, i;
          op = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea comprar este coche?", "Eliminar", JOptionPane.YES_NO_OPTION);
          
          ArrayList<Autos> auto = Helper.traerDatos(ruta);
          if (op == JOptionPane.YES_OPTION){
            CompradoresAutos a = new CompradoresAutos(null,true);
            a.setVisible(true);
          }
    }//GEN-LAST:event_cmbComprarActionPerformed

    private void tblAutosNuevosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAutosNuevosMouseClicked
        int i;
        Autos p;
        ArrayList<Autos> autos = Helper.traerDatos(ruta);
        i = tblAutosNuevos.getSelectedRow();
        
        p = auto.get(i);
        
        p.getMarca();
        p.getModelo();
        
        
    }//GEN-LAST:event_tblAutosNuevosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AutosNuevos dialog = new AutosNuevos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbComprar;
    private javax.swing.JButton cmbListar;
    private javax.swing.JComboBox cmbMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutosNuevos;
    // End of variables declaration//GEN-END:variables
}
